# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170402_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
