# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('life', 'Life'), ('tech', 'Tech')], max_length=20, null=True),
        ),
    ]
