# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0011_auto_20170404_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike'), ('init', 'init')], max_length=20, null=True)),
                ('of_Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_tickets', to='firstapp.Article')),
                ('of_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
