# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0012_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
