# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_article_belong_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='belong_to',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
